#!/bin/sh

buildApp() {
    unzip $VERSION.zip
    cd ./godemon-$VERSION
    go build
}

prepareDirs() {
    mkdir ~/.godemon
    mkdir ~/.godemon/logs/
    mkdir ~/.godemon/bin/
}

removing() {
  cd ..
  sudo rm -r godemon-$VERSION
  sudo rm -r $VERSION.zip
}

printf "**********_________________***********\n*********/*****************\**********\n********/*******************\*********\n*******/_____________________\********\n*********WELCOME TO GODEMON***********\n*************UPDATE****************\n\n"

printf "\nWhat version do you want to install: "
read VERSION
printf "\nDo you want to do this: \n1. Global \n2. Local \n"
printf "\nAnswer: "
read GL

wget https://github.com/nProgrammer/godemon/archive/$VERSION.zip

if [ "$GL" = "2" ]
then
  buildApp
  prepareDirs
  sudo mv godemon ~/.godemon/bin/
  sudo chmod 777 ~/.godemon/bin/godemon
  removing
elif [ "$GL" = "1" ]
then
  buildApp
  prepareDirs
  sudo mkdir /usr/local/.godemon/bin/
  sudo mv godemon /usr/local/.godemon/bin/
  sudo chmod 777 /usr/local/.godemon/bin/godemon
  removing
fi

printf "\nEverything done \n"